<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INDP277LT" failures="2" tests="4" name="Test" time="0.256" errors="0" timestamp="2021-01-09T02:46:49 IST">
  <testcase classname="listener.Demo" name="testMethod01" time="0.052">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at listener.Demo.testMethod01(Demo.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testMethod01 -->
  <testcase classname="listener.Demo" name="testMethod02" time="0.004"/>
  <testcase classname="listener.Demo2" name="testMethod03" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at listener.Demo2.testMethod03(Demo2.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testMethod03 -->
  <testcase classname="listener.Demo2" name="testMethod04" time="0.003"/>
</testsuite> <!-- Test -->
